language: erlang

otp_release:
  - 17.1

env:
  - ELIXIR_VERSION=0.15.1
  - ELIXIR_VERSION=1.0.0-rc1
  - ELIXIR_VERSION=1.0.0-rc2

install:
  - wget https://github.com/elixir-lang/elixir/releases/download/v$ELIXIR_VERSION/Precompiled.zip
  - unzip -d elixir Precompiled.zip

before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
  - MIX_ENV=test mix compile

script:
  - mix test --trace
